dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/argon2_cffi/.eggs
git:
  # We do this by hand depending on TOXENV.
  submodules: false


language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "pypy2.7-5.8.0"
      env: TOXENV=pypy
    - python: "pypy3.5-5.9.0"
      env: TOXENV=pypy3

    # Meta
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=manifest
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=readme
    - python: "3.6"
      env: TOXENV=system-argon2


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov
  - |
    if [[ "${TOXENV}" == "system-argon2" ]]; then
        wget http://de.archive.ubuntu.com/ubuntu/pool/universe/a/argon2/libargon2-0_0~20161029-1_amd64.deb
        wget http://de.archive.ubuntu.com/ubuntu/pool/universe/a/argon2/libargon2-0-dev_0~20161029-1_amd64.deb
        sudo dpkg -i libargon2-0_0~20161029-1_amd64.deb
        sudo dpkg -i libargon2-0-dev_0~20161029-1_amd64.deb
    else
        # If the system argon2 library should not be used, clone the submodule containing the vendored argon2 library
        git submodule update --init --recursive
    fi


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
