sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/argon2_cffi/.eggs

language: python


matrix:
  include:
    - python: "2.7"  # these are just to make travis's UI a bit prettier
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "pypy"
      env: TOXENV=pypy
    - python: pypy3.3-5.2-alpha1
      env: TOXENV=pypy3

    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "3.5"
      env: TOXENV=manifest
    - python: "3.5"
      env: TOXENV=docs
    - python: "3.5"
      env: TOXENV=readme

install:
  - |
    if [[ "${TOXENV}" = pypy* ]]; then
        git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install pypy-5.4.1
        pyenv global pypy-5.4.1
    fi
  - pip install tox-travis

script:
  - |
    # activate the PyPy env we installed via our custom pyenv in the install stage
    if [[ "${TOXENV}" == "pypy" ]]; then
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
    fi
  - tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
